-- V1: the core registry.
--
-- Flyway applies this exactly once and records it in flyway_schema_history.
-- The file is IMMUTABLE after it has been applied anywhere: to change the
-- schema you add V2, you never edit V1. That is the same immutability rule
-- we apply to artifacts, one layer down.

CREATE TABLE tools (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(128) NOT NULL,
    description VARCHAR(512),
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uk_tools_name UNIQUE (name)
);

CREATE TABLE tool_versions (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tool_id         BIGINT       NOT NULL,
    version         VARCHAR(64)  NOT NULL,
    major_part      INTEGER      NOT NULL,
    minor_part      INTEGER      NOT NULL,
    patch_part      INTEGER      NOT NULL,
    artifact_path   VARCHAR(512) NOT NULL,
    -- VARCHAR, not CHAR: PostgreSQL reports CHAR as 'bpchar', which does not
    -- match the varchar(64) that Hibernate expects for a String field - and
    -- `ddl-auto: validate` (correctly) refuses to start on that mismatch.
    checksum_sha256 VARCHAR(64),
    status          VARCHAR(32)  NOT NULL,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT fk_tool_versions_tool
        FOREIGN KEY (tool_id) REFERENCES tools (id) ON DELETE CASCADE,

    -- THE immutability guarantee: the same (tool, version) can exist only once.
    CONSTRAINT uk_tool_versions_tool_version UNIQUE (tool_id, version),

    CONSTRAINT ck_tool_versions_checksum_len
        CHECK (checksum_sha256 IS NULL OR char_length(checksum_sha256) = 64),

    CONSTRAINT ck_tool_versions_status
        CHECK (status IN ('DRAFT', 'PUBLISHED', 'DEPRECATED', 'REVOKED'))
);

-- Supports "list versions of tool X, newest first" without a full scan.
CREATE INDEX idx_tool_versions_lookup
    ON tool_versions (tool_id, major_part DESC, minor_part DESC, patch_part DESC);
