-- V2: which client consumes which version of which tool.
--
-- V1 is already applied, so it must never be edited - Flyway stores a checksum
-- of every applied migration and refuses to run if one changed underneath it.
-- Schema evolution is append-only, exactly like artifact versions.

CREATE TABLE clients (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(128) NOT NULL,
    description VARCHAR(512),
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uk_clients_name UNIQUE (name)
);

CREATE TABLE client_tool_configuration (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id         BIGINT      NOT NULL,
    tool_id           BIGINT      NOT NULL,

    -- PINNED = always this exact version. LATEST = explicitly opted in to float.
    selector          VARCHAR(16) NOT NULL,

    -- A FOREIGN KEY, not a version string. Two consequences we want:
    --   1. You cannot pin a client to a version that does not exist.
    --   2. ON DELETE RESTRICT: you cannot delete a version a client depends on.
    -- Referential integrity does the work that validation code would otherwise
    -- have to do on every single write path.
    pinned_version_id BIGINT,

    updated_at        TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT fk_ctc_client
        FOREIGN KEY (client_id) REFERENCES clients (id) ON DELETE CASCADE,
    CONSTRAINT fk_ctc_tool
        FOREIGN KEY (tool_id) REFERENCES tools (id) ON DELETE CASCADE,
    CONSTRAINT fk_ctc_pinned_version
        FOREIGN KEY (pinned_version_id) REFERENCES tool_versions (id) ON DELETE RESTRICT,

    -- One decision per (client, tool). A client cannot want two versions of
    -- the same tool at once.
    CONSTRAINT uk_ctc_client_tool UNIQUE (client_id, tool_id),

    CONSTRAINT ck_ctc_selector
        CHECK (selector IN ('PINNED', 'LATEST')),

    -- The model invariant, enforced by the database rather than by hope:
    -- PINNED must name a version; LATEST must not.
    CONSTRAINT ck_ctc_selector_consistency CHECK (
        (selector = 'PINNED' AND pinned_version_id IS NOT NULL) OR
        (selector = 'LATEST' AND pinned_version_id IS NULL)
    )
);

CREATE INDEX idx_ctc_client ON client_tool_configuration (client_id);
